### ISSUE TITLE
I'm probably very dumb... (Turn on VPN for download, if download doesn't work)

### ISSUE THREAD

**Issue by HyperPoss** [DqwertyC/mazegen-datapack#2]
**I'm probably very dumb but can't see where to download the file?** ("Download Zip" doesn't work, and "Releases" is empty)
Sorry, i asking really stupid question... (My english is not very good)

**Comment by DqwertyC** [comment]
Hmm.. "Download Zip" is the option I've been using. You may need to unzip the contents and copy the "Maze" folder from the zip to your datapacks folder.

**Comment by HyperPoss** [comment]
Oh. See these screenshots, I solved the problem with a simple VPN. **I'm from Ukraine, but I didn't even think about VPN for downloading from GitHub.** Now, I can download files from GitHub normally) **Anyway, thank you!!!** **GoodBye!**
![Screenshot (262)](https://user-images.githubusercontent.com/52428534/141593606-fa76e5f9-fa68-493e-9c9c-c774c12cbb04.png)
![Screenshot (263)](https://user-images.githubusercontent.com/52428534/141593610-7acde60c-e4b4-4d12-a3d9-e5fa984f8480.png)
![Screenshot (264)](https://user-images.githubusercontent.com/52428534/141593611-85e5b9c3-7237-4c22-aff6-c4f950dd49ee.png)
![Screenshot (265)](https://user-images.githubusercontent.com/52428534/141593615-0025d829-8b46-44a7-bb03-10a9c09a9200.png)
